# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-15 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
