# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-16 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190116_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publicate_date', '-id'], 'verbose_name': '书籍', 'verbose_name_plural': '书籍'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
