"""empty message

Revision ID: 2a4d08ce67fa
Revises: 8fda116c460b
Create Date: 2019-01-02 21:04:14.691918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4d08ce67fa'
down_revision = '8fda116c460b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wife', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'wife', ['teacher_id'])
    op.create_foreign_key(None, 'wife', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wife', type_='foreignkey')
    op.drop_constraint(None, 'wife', type_='unique')
    op.drop_column('wife', 'teacher_id')
    # ### end Alembic commands ###
