"""empty message

Revision ID: 64a261e3922b
Revises: df82f0bf3605
Create Date: 2018-12-29 11:17:54.223054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a261e3922b'
down_revision = 'df82f0bf3605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isActive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isActive')
    # ### end Alembic commands ###
