"""empty message

Revision ID: 8fda116c460b
Revises: cd743470c233
Create Date: 2019-01-02 16:33:10.145968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fda116c460b'
down_revision = 'cd743470c233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wife', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'wife', ['user_id'])
    op.create_foreign_key(None, 'wife', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wife', type_='foreignkey')
    op.drop_constraint(None, 'wife', type_='unique')
    op.drop_column('wife', 'user_id')
    # ### end Alembic commands ###
