# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-21 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_goodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='GoodType',
            new_name='GoodsType',
        ),
    ]
