# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-21 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190121_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
