"""empty message

Revision ID: 41734bd6c24a
Revises: 
Create Date: 2019-01-04 20:13:52.367468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41734bd6c24a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=100), nullable=True),
    sa.Column('upwd', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
