"""empty message

Revision ID: c2b52796d38d
Revises: 64a261e3922b
Create Date: 2018-12-29 11:20:31.226198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b52796d38d'
down_revision = '64a261e3922b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=30), nullable=True),
    sa.Column('uage', sa.Integer(), nullable=True),
    sa.Column('uemail', sa.String(length=200), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
